// Code generated by ent, DO NOT EDIT.

package company

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jp-ryuji/go-ddd/internal/infrastructure/postgres/entgen/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldID, id))
}

// RenterID applies equality check predicate on the "renter_id" field. It's identical to RenterIDEQ.
func RenterID(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldRenterID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldTenantID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldName, v))
}

// CompanySize applies equality check predicate on the "company_size" field. It's identical to CompanySizeEQ.
func CompanySize(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCompanySize, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldDeletedAt, v))
}

// RenterIDEQ applies the EQ predicate on the "renter_id" field.
func RenterIDEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldRenterID, v))
}

// RenterIDNEQ applies the NEQ predicate on the "renter_id" field.
func RenterIDNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldRenterID, v))
}

// RenterIDIn applies the In predicate on the "renter_id" field.
func RenterIDIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldRenterID, vs...))
}

// RenterIDNotIn applies the NotIn predicate on the "renter_id" field.
func RenterIDNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldRenterID, vs...))
}

// RenterIDGT applies the GT predicate on the "renter_id" field.
func RenterIDGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldRenterID, v))
}

// RenterIDGTE applies the GTE predicate on the "renter_id" field.
func RenterIDGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldRenterID, v))
}

// RenterIDLT applies the LT predicate on the "renter_id" field.
func RenterIDLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldRenterID, v))
}

// RenterIDLTE applies the LTE predicate on the "renter_id" field.
func RenterIDLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldRenterID, v))
}

// RenterIDContains applies the Contains predicate on the "renter_id" field.
func RenterIDContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldRenterID, v))
}

// RenterIDHasPrefix applies the HasPrefix predicate on the "renter_id" field.
func RenterIDHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldRenterID, v))
}

// RenterIDHasSuffix applies the HasSuffix predicate on the "renter_id" field.
func RenterIDHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldRenterID, v))
}

// RenterIDEqualFold applies the EqualFold predicate on the "renter_id" field.
func RenterIDEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldRenterID, v))
}

// RenterIDContainsFold applies the ContainsFold predicate on the "renter_id" field.
func RenterIDContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldRenterID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldTenantID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldName, v))
}

// CompanySizeEQ applies the EQ predicate on the "company_size" field.
func CompanySizeEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCompanySize, v))
}

// CompanySizeNEQ applies the NEQ predicate on the "company_size" field.
func CompanySizeNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldCompanySize, v))
}

// CompanySizeIn applies the In predicate on the "company_size" field.
func CompanySizeIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldCompanySize, vs...))
}

// CompanySizeNotIn applies the NotIn predicate on the "company_size" field.
func CompanySizeNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldCompanySize, vs...))
}

// CompanySizeGT applies the GT predicate on the "company_size" field.
func CompanySizeGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldCompanySize, v))
}

// CompanySizeGTE applies the GTE predicate on the "company_size" field.
func CompanySizeGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldCompanySize, v))
}

// CompanySizeLT applies the LT predicate on the "company_size" field.
func CompanySizeLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldCompanySize, v))
}

// CompanySizeLTE applies the LTE predicate on the "company_size" field.
func CompanySizeLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldCompanySize, v))
}

// CompanySizeContains applies the Contains predicate on the "company_size" field.
func CompanySizeContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldCompanySize, v))
}

// CompanySizeHasPrefix applies the HasPrefix predicate on the "company_size" field.
func CompanySizeHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldCompanySize, v))
}

// CompanySizeHasSuffix applies the HasSuffix predicate on the "company_size" field.
func CompanySizeHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldCompanySize, v))
}

// CompanySizeEqualFold applies the EqualFold predicate on the "company_size" field.
func CompanySizeEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldCompanySize, v))
}

// CompanySizeContainsFold applies the ContainsFold predicate on the "company_size" field.
func CompanySizeContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldCompanySize, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldDeletedAt))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRenter applies the HasEdge predicate on the "renter" edge.
func HasRenter() predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RenterTable, RenterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRenterWith applies the HasEdge predicate on the "renter" edge with a given conditions (other predicates).
func HasRenterWith(preds ...predicate.Renter) predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := newRenterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Company) predicate.Company {
	return predicate.Company(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Company) predicate.Company {
	return predicate.Company(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Company) predicate.Company {
	return predicate.Company(sql.NotPredicates(p))
}
