version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - exhaustive
    - gocognit
    - goconst
    - goheader
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - dupl
          - funlen
          - goconst
          - gosec
          - noctx
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/ent/car/
      - internal/ent/caroption/
      - internal/ent/company/
      - internal/ent/individual/
      - internal/ent/rental/
      - internal/ent/rentaloption/
      - internal/ent/renter/
      - internal/ent/tenant/
      - internal/ent/car.go
      - internal/ent/car_create.go
      - internal/ent/car_delete.go
      - internal/ent/car_query.go
      - internal/ent/car_update.go
      - internal/ent/caroption.go
      - internal/ent/caroption_create.go
      - internal/ent/caroption_delete.go
      - internal/ent/caroption_query.go
      - internal/ent/caroption_update.go
      - internal/ent/company.go
      - internal/ent/company_create.go
      - internal/ent/company_delete.go
      - internal/ent/company_query.go
      - internal/ent/company_update.go
      - internal/ent/individual.go
      - internal/ent/individual_create.go
      - internal/ent/individual_delete.go
      - internal/ent/individual_query.go
      - internal/ent/individual_update.go
      - internal/ent/rental.go
      - internal/ent/rental_create.go
      - internal/ent/rental_delete.go
      - internal/ent/rental_query.go
      - internal/ent/rental_update.go
      - internal/ent/rentaloption.go
      - internal/ent/rentaloption_create.go
      - internal/ent/rentaloption_delete.go
      - internal/ent/rentaloption_query.go
      - internal/ent/rentaloption_update.go
      - internal/ent/renter.go
      - internal/ent/renter_create.go
      - internal/ent/renter_delete.go
      - internal/ent/renter_query.go
      - internal/ent/renter_update.go
      - internal/ent/tenant.go
      - internal/ent/tenant_create.go
      - internal/ent/tenant_delete.go
      - internal/ent/tenant_query.go
      - internal/ent/tenant_update.go
      - internal/ent/client.go
      - internal/ent/ent.go
      - internal/ent/mutation.go
      - internal/ent/runtime.go
      - internal/ent/tx.go
      - internal/ent/gql_*.go
      - internal/ent/enttest/
      - internal/ent/hook/
      - internal/ent/migrate/
      - internal/ent/predicate/
      - internal/ent/runtime/
      - internal/graphql/schema.resolvers.go
      - internal/graphql/generated.go
      - internal/graphql/model/
      - internal/infrastructure/postgres/gen/
      - schema/graphql/
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/ent/car/
      - internal/ent/caroption/
      - internal/ent/company/
      - internal/ent/individual/
      - internal/ent/rental/
      - internal/ent/rentaloption/
      - internal/ent/renter/
      - internal/ent/tenant/
      - internal/ent/car.go
      - internal/ent/car_create.go
      - internal/ent/car_delete.go
      - internal/ent/car_query.go
      - internal/ent/car_update.go
      - internal/ent/caroption.go
      - internal/ent/caroption_create.go
      - internal/ent/caroption_delete.go
      - internal/ent/caroption_query.go
      - internal/ent/caroption_update.go
      - internal/ent/company.go
      - internal/ent/company_create.go
      - internal/ent/company_delete.go
      - internal/ent/company_query.go
      - internal/ent/company_update.go
      - internal/ent/individual.go
      - internal/ent/individual_create.go
      - internal/ent/individual_delete.go
      - internal/ent/individual_query.go
      - internal/ent/individual_update.go
      - internal/ent/rental.go
      - internal/ent/rental_create.go
      - internal/ent/rental_delete.go
      - internal/ent/rental_query.go
      - internal/ent/rental_update.go
      - internal/ent/rentaloption.go
      - internal/ent/rentaloption_create.go
      - internal/ent/rentaloption_delete.go
      - internal/ent/rentaloption_query.go
      - internal/ent/rentaloption_update.go
      - internal/ent/renter.go
      - internal/ent/renter_create.go
      - internal/ent/renter_delete.go
      - internal/ent/renter_query.go
      - internal/ent/renter_update.go
      - internal/ent/tenant.go
      - internal/ent/tenant_create.go
      - internal/ent/tenant_delete.go
      - internal/ent/tenant_query.go
      - internal/ent/tenant_update.go
      - internal/ent/client.go
      - internal/ent/ent.go
      - internal/ent/mutation.go
      - internal/ent/runtime.go
      - internal/ent/tx.go
      - internal/ent/gql_*.go
      - internal/ent/enttest/
      - internal/ent/hook/
      - internal/ent/migrate/
      - internal/ent/predicate/
      - internal/ent/runtime/
      - internal/graphql/schema.resolvers.go
      - internal/graphql/generated.go
      - internal/graphql/model/
      - internal/infrastructure/postgres/gen/
      - schema/graphql/
