services:
  postgres:
    image: postgres:17
    ports:
      - '${DB_PORT_EXTERNAL:-5433}:${DB_PORT:-5432}'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 1s
      timeout: 3s
      retries: 5

  redis:
    image: redis:8
    ports:
      - '${REDIS_PORT_EXTERNAL:-6380}:${REDIS_PORT:-6379}'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
