services:
  postgres:
    image: postgres:17
    ports:
      - '${POSTGRES_PORT_EXTERNAL:-5433}:${POSTGRES_PORT:-5432}'
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DBNAME}']
      interval: 1s
      timeout: 3s
      retries: 5

  redis:
    image: redis:8
    ports:
      - '${REDIS_PORT_EXTERNAL:-6380}:${REDIS_PORT:-6379}'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
