// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jp-ryuji/go-sample/internal/ent/caroption"
	"github.com/jp-ryuji/go-sample/internal/ent/rentaloption"
	"github.com/jp-ryuji/go-sample/internal/ent/tenant"
)

// CarOptionCreate is the builder for creating a CarOption entity.
type CarOptionCreate struct {
	config
	mutation *CarOptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *CarOptionCreate) SetName(v string) *CarOptionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *CarOptionCreate) SetTenantID(v string) *CarOptionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CarOptionCreate) SetID(v string) *CarOptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *CarOptionCreate) SetTenant(v *Tenant) *CarOptionCreate {
	return _c.SetTenantID(v.ID)
}

// AddRentalOptionIDs adds the "rental_options" edge to the RentalOption entity by IDs.
func (_c *CarOptionCreate) AddRentalOptionIDs(ids ...string) *CarOptionCreate {
	_c.mutation.AddRentalOptionIDs(ids...)
	return _c
}

// AddRentalOptions adds the "rental_options" edges to the RentalOption entity.
func (_c *CarOptionCreate) AddRentalOptions(v ...*RentalOption) *CarOptionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRentalOptionIDs(ids...)
}

// Mutation returns the CarOptionMutation object of the builder.
func (_c *CarOptionCreate) Mutation() *CarOptionMutation {
	return _c.mutation
}

// Save creates the CarOption in the database.
func (_c *CarOptionCreate) Save(ctx context.Context) (*CarOption, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CarOptionCreate) SaveX(ctx context.Context) *CarOption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarOptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarOptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CarOptionCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CarOption.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := caroption.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CarOption.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "CarOption.tenant_id"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := caroption.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "CarOption.id": %w`, err)}
		}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "CarOption.tenant"`)}
	}
	return nil
}

func (_c *CarOptionCreate) sqlSave(ctx context.Context) (*CarOption, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CarOption.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CarOptionCreate) createSpec() (*CarOption, *sqlgraph.CreateSpec) {
	var (
		_node = &CarOption{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(caroption.Table, sqlgraph.NewFieldSpec(caroption.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(caroption.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   caroption.TenantTable,
			Columns: []string{caroption.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RentalOptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   caroption.RentalOptionsTable,
			Columns: []string{caroption.RentalOptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rentaloption.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarOption.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarOptionUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *CarOptionCreate) OnConflict(opts ...sql.ConflictOption) *CarOptionUpsertOne {
	_c.conflict = opts
	return &CarOptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarOption.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarOptionCreate) OnConflictColumns(columns ...string) *CarOptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarOptionUpsertOne{
		create: _c,
	}
}

type (
	// CarOptionUpsertOne is the builder for "upsert"-ing
	//  one CarOption node.
	CarOptionUpsertOne struct {
		create *CarOptionCreate
	}

	// CarOptionUpsert is the "OnConflict" setter.
	CarOptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *CarOptionUpsert) SetName(v string) *CarOptionUpsert {
	u.Set(caroption.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CarOptionUpsert) UpdateName() *CarOptionUpsert {
	u.SetExcluded(caroption.FieldName)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *CarOptionUpsert) SetTenantID(v string) *CarOptionUpsert {
	u.Set(caroption.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *CarOptionUpsert) UpdateTenantID() *CarOptionUpsert {
	u.SetExcluded(caroption.FieldTenantID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CarOption.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(caroption.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CarOptionUpsertOne) UpdateNewValues() *CarOptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(caroption.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarOption.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CarOptionUpsertOne) Ignore() *CarOptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarOptionUpsertOne) DoNothing() *CarOptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarOptionCreate.OnConflict
// documentation for more info.
func (u *CarOptionUpsertOne) Update(set func(*CarOptionUpsert)) *CarOptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarOptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CarOptionUpsertOne) SetName(v string) *CarOptionUpsertOne {
	return u.Update(func(s *CarOptionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CarOptionUpsertOne) UpdateName() *CarOptionUpsertOne {
	return u.Update(func(s *CarOptionUpsert) {
		s.UpdateName()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *CarOptionUpsertOne) SetTenantID(v string) *CarOptionUpsertOne {
	return u.Update(func(s *CarOptionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *CarOptionUpsertOne) UpdateTenantID() *CarOptionUpsertOne {
	return u.Update(func(s *CarOptionUpsert) {
		s.UpdateTenantID()
	})
}

// Exec executes the query.
func (u *CarOptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarOptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarOptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CarOptionUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CarOptionUpsertOne.ID is not supported by MySQL driver. Use CarOptionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CarOptionUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CarOptionCreateBulk is the builder for creating many CarOption entities in bulk.
type CarOptionCreateBulk struct {
	config
	err      error
	builders []*CarOptionCreate
	conflict []sql.ConflictOption
}

// Save creates the CarOption entities in the database.
func (_c *CarOptionCreateBulk) Save(ctx context.Context) ([]*CarOption, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CarOption, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CarOptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CarOptionCreateBulk) SaveX(ctx context.Context) []*CarOption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarOptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarOptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarOption.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarOptionUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *CarOptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *CarOptionUpsertBulk {
	_c.conflict = opts
	return &CarOptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarOption.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarOptionCreateBulk) OnConflictColumns(columns ...string) *CarOptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarOptionUpsertBulk{
		create: _c,
	}
}

// CarOptionUpsertBulk is the builder for "upsert"-ing
// a bulk of CarOption nodes.
type CarOptionUpsertBulk struct {
	create *CarOptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CarOption.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(caroption.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CarOptionUpsertBulk) UpdateNewValues() *CarOptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(caroption.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarOption.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CarOptionUpsertBulk) Ignore() *CarOptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarOptionUpsertBulk) DoNothing() *CarOptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarOptionCreateBulk.OnConflict
// documentation for more info.
func (u *CarOptionUpsertBulk) Update(set func(*CarOptionUpsert)) *CarOptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarOptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CarOptionUpsertBulk) SetName(v string) *CarOptionUpsertBulk {
	return u.Update(func(s *CarOptionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CarOptionUpsertBulk) UpdateName() *CarOptionUpsertBulk {
	return u.Update(func(s *CarOptionUpsert) {
		s.UpdateName()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *CarOptionUpsertBulk) SetTenantID(v string) *CarOptionUpsertBulk {
	return u.Update(func(s *CarOptionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *CarOptionUpsertBulk) UpdateTenantID() *CarOptionUpsertBulk {
	return u.Update(func(s *CarOptionUpsert) {
		s.UpdateTenantID()
	})
}

// Exec executes the query.
func (u *CarOptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CarOptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarOptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarOptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
