// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jp-ryuji/go-sample/internal/ent/caroption"
	"github.com/jp-ryuji/go-sample/internal/ent/rental"
	"github.com/jp-ryuji/go-sample/internal/ent/rentaloption"
	"github.com/jp-ryuji/go-sample/internal/ent/tenant"
)

// RentalOptionCreate is the builder for creating a RentalOption entity.
type RentalOptionCreate struct {
	config
	mutation *RentalOptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCount sets the "count" field.
func (_c *RentalOptionCreate) SetCount(v int) *RentalOptionCreate {
	_c.mutation.SetCount(v)
	return _c
}

// SetRentalID sets the "rental_id" field.
func (_c *RentalOptionCreate) SetRentalID(v string) *RentalOptionCreate {
	_c.mutation.SetRentalID(v)
	return _c
}

// SetOptionID sets the "option_id" field.
func (_c *RentalOptionCreate) SetOptionID(v string) *RentalOptionCreate {
	_c.mutation.SetOptionID(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *RentalOptionCreate) SetTenantID(v string) *RentalOptionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RentalOptionCreate) SetID(v string) *RentalOptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *RentalOptionCreate) SetTenant(v *Tenant) *RentalOptionCreate {
	return _c.SetTenantID(v.ID)
}

// SetRental sets the "rental" edge to the Rental entity.
func (_c *RentalOptionCreate) SetRental(v *Rental) *RentalOptionCreate {
	return _c.SetRentalID(v.ID)
}

// SetOption sets the "option" edge to the CarOption entity.
func (_c *RentalOptionCreate) SetOption(v *CarOption) *RentalOptionCreate {
	return _c.SetOptionID(v.ID)
}

// Mutation returns the RentalOptionMutation object of the builder.
func (_c *RentalOptionCreate) Mutation() *RentalOptionMutation {
	return _c.mutation
}

// Save creates the RentalOption in the database.
func (_c *RentalOptionCreate) Save(ctx context.Context) (*RentalOption, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RentalOptionCreate) SaveX(ctx context.Context) *RentalOption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RentalOptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RentalOptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RentalOptionCreate) check() error {
	if _, ok := _c.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "RentalOption.count"`)}
	}
	if _, ok := _c.mutation.RentalID(); !ok {
		return &ValidationError{Name: "rental_id", err: errors.New(`ent: missing required field "RentalOption.rental_id"`)}
	}
	if _, ok := _c.mutation.OptionID(); !ok {
		return &ValidationError{Name: "option_id", err: errors.New(`ent: missing required field "RentalOption.option_id"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "RentalOption.tenant_id"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := rentaloption.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "RentalOption.id": %w`, err)}
		}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "RentalOption.tenant"`)}
	}
	if len(_c.mutation.RentalIDs()) == 0 {
		return &ValidationError{Name: "rental", err: errors.New(`ent: missing required edge "RentalOption.rental"`)}
	}
	if len(_c.mutation.OptionIDs()) == 0 {
		return &ValidationError{Name: "option", err: errors.New(`ent: missing required edge "RentalOption.option"`)}
	}
	return nil
}

func (_c *RentalOptionCreate) sqlSave(ctx context.Context) (*RentalOption, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RentalOption.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RentalOptionCreate) createSpec() (*RentalOption, *sqlgraph.CreateSpec) {
	var (
		_node = &RentalOption{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rentaloption.Table, sqlgraph.NewFieldSpec(rentaloption.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Count(); ok {
		_spec.SetField(rentaloption.FieldCount, field.TypeInt, value)
		_node.Count = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rentaloption.TenantTable,
			Columns: []string{rentaloption.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rentaloption.RentalTable,
			Columns: []string{rentaloption.RentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rental.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RentalID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rentaloption.OptionTable,
			Columns: []string{rentaloption.OptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(caroption.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OptionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RentalOption.Create().
//		SetCount(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RentalOptionUpsert) {
//			SetCount(v+v).
//		}).
//		Exec(ctx)
func (_c *RentalOptionCreate) OnConflict(opts ...sql.ConflictOption) *RentalOptionUpsertOne {
	_c.conflict = opts
	return &RentalOptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RentalOption.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RentalOptionCreate) OnConflictColumns(columns ...string) *RentalOptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RentalOptionUpsertOne{
		create: _c,
	}
}

type (
	// RentalOptionUpsertOne is the builder for "upsert"-ing
	//  one RentalOption node.
	RentalOptionUpsertOne struct {
		create *RentalOptionCreate
	}

	// RentalOptionUpsert is the "OnConflict" setter.
	RentalOptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetCount sets the "count" field.
func (u *RentalOptionUpsert) SetCount(v int) *RentalOptionUpsert {
	u.Set(rentaloption.FieldCount, v)
	return u
}

// UpdateCount sets the "count" field to the value that was provided on create.
func (u *RentalOptionUpsert) UpdateCount() *RentalOptionUpsert {
	u.SetExcluded(rentaloption.FieldCount)
	return u
}

// AddCount adds v to the "count" field.
func (u *RentalOptionUpsert) AddCount(v int) *RentalOptionUpsert {
	u.Add(rentaloption.FieldCount, v)
	return u
}

// SetRentalID sets the "rental_id" field.
func (u *RentalOptionUpsert) SetRentalID(v string) *RentalOptionUpsert {
	u.Set(rentaloption.FieldRentalID, v)
	return u
}

// UpdateRentalID sets the "rental_id" field to the value that was provided on create.
func (u *RentalOptionUpsert) UpdateRentalID() *RentalOptionUpsert {
	u.SetExcluded(rentaloption.FieldRentalID)
	return u
}

// SetOptionID sets the "option_id" field.
func (u *RentalOptionUpsert) SetOptionID(v string) *RentalOptionUpsert {
	u.Set(rentaloption.FieldOptionID, v)
	return u
}

// UpdateOptionID sets the "option_id" field to the value that was provided on create.
func (u *RentalOptionUpsert) UpdateOptionID() *RentalOptionUpsert {
	u.SetExcluded(rentaloption.FieldOptionID)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *RentalOptionUpsert) SetTenantID(v string) *RentalOptionUpsert {
	u.Set(rentaloption.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *RentalOptionUpsert) UpdateTenantID() *RentalOptionUpsert {
	u.SetExcluded(rentaloption.FieldTenantID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RentalOption.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rentaloption.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RentalOptionUpsertOne) UpdateNewValues() *RentalOptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(rentaloption.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RentalOption.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RentalOptionUpsertOne) Ignore() *RentalOptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RentalOptionUpsertOne) DoNothing() *RentalOptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RentalOptionCreate.OnConflict
// documentation for more info.
func (u *RentalOptionUpsertOne) Update(set func(*RentalOptionUpsert)) *RentalOptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RentalOptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCount sets the "count" field.
func (u *RentalOptionUpsertOne) SetCount(v int) *RentalOptionUpsertOne {
	return u.Update(func(s *RentalOptionUpsert) {
		s.SetCount(v)
	})
}

// AddCount adds v to the "count" field.
func (u *RentalOptionUpsertOne) AddCount(v int) *RentalOptionUpsertOne {
	return u.Update(func(s *RentalOptionUpsert) {
		s.AddCount(v)
	})
}

// UpdateCount sets the "count" field to the value that was provided on create.
func (u *RentalOptionUpsertOne) UpdateCount() *RentalOptionUpsertOne {
	return u.Update(func(s *RentalOptionUpsert) {
		s.UpdateCount()
	})
}

// SetRentalID sets the "rental_id" field.
func (u *RentalOptionUpsertOne) SetRentalID(v string) *RentalOptionUpsertOne {
	return u.Update(func(s *RentalOptionUpsert) {
		s.SetRentalID(v)
	})
}

// UpdateRentalID sets the "rental_id" field to the value that was provided on create.
func (u *RentalOptionUpsertOne) UpdateRentalID() *RentalOptionUpsertOne {
	return u.Update(func(s *RentalOptionUpsert) {
		s.UpdateRentalID()
	})
}

// SetOptionID sets the "option_id" field.
func (u *RentalOptionUpsertOne) SetOptionID(v string) *RentalOptionUpsertOne {
	return u.Update(func(s *RentalOptionUpsert) {
		s.SetOptionID(v)
	})
}

// UpdateOptionID sets the "option_id" field to the value that was provided on create.
func (u *RentalOptionUpsertOne) UpdateOptionID() *RentalOptionUpsertOne {
	return u.Update(func(s *RentalOptionUpsert) {
		s.UpdateOptionID()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *RentalOptionUpsertOne) SetTenantID(v string) *RentalOptionUpsertOne {
	return u.Update(func(s *RentalOptionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *RentalOptionUpsertOne) UpdateTenantID() *RentalOptionUpsertOne {
	return u.Update(func(s *RentalOptionUpsert) {
		s.UpdateTenantID()
	})
}

// Exec executes the query.
func (u *RentalOptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RentalOptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RentalOptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RentalOptionUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RentalOptionUpsertOne.ID is not supported by MySQL driver. Use RentalOptionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RentalOptionUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RentalOptionCreateBulk is the builder for creating many RentalOption entities in bulk.
type RentalOptionCreateBulk struct {
	config
	err      error
	builders []*RentalOptionCreate
	conflict []sql.ConflictOption
}

// Save creates the RentalOption entities in the database.
func (_c *RentalOptionCreateBulk) Save(ctx context.Context) ([]*RentalOption, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RentalOption, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RentalOptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RentalOptionCreateBulk) SaveX(ctx context.Context) []*RentalOption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RentalOptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RentalOptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RentalOption.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RentalOptionUpsert) {
//			SetCount(v+v).
//		}).
//		Exec(ctx)
func (_c *RentalOptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *RentalOptionUpsertBulk {
	_c.conflict = opts
	return &RentalOptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RentalOption.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RentalOptionCreateBulk) OnConflictColumns(columns ...string) *RentalOptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RentalOptionUpsertBulk{
		create: _c,
	}
}

// RentalOptionUpsertBulk is the builder for "upsert"-ing
// a bulk of RentalOption nodes.
type RentalOptionUpsertBulk struct {
	create *RentalOptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RentalOption.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rentaloption.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RentalOptionUpsertBulk) UpdateNewValues() *RentalOptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(rentaloption.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RentalOption.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RentalOptionUpsertBulk) Ignore() *RentalOptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RentalOptionUpsertBulk) DoNothing() *RentalOptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RentalOptionCreateBulk.OnConflict
// documentation for more info.
func (u *RentalOptionUpsertBulk) Update(set func(*RentalOptionUpsert)) *RentalOptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RentalOptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCount sets the "count" field.
func (u *RentalOptionUpsertBulk) SetCount(v int) *RentalOptionUpsertBulk {
	return u.Update(func(s *RentalOptionUpsert) {
		s.SetCount(v)
	})
}

// AddCount adds v to the "count" field.
func (u *RentalOptionUpsertBulk) AddCount(v int) *RentalOptionUpsertBulk {
	return u.Update(func(s *RentalOptionUpsert) {
		s.AddCount(v)
	})
}

// UpdateCount sets the "count" field to the value that was provided on create.
func (u *RentalOptionUpsertBulk) UpdateCount() *RentalOptionUpsertBulk {
	return u.Update(func(s *RentalOptionUpsert) {
		s.UpdateCount()
	})
}

// SetRentalID sets the "rental_id" field.
func (u *RentalOptionUpsertBulk) SetRentalID(v string) *RentalOptionUpsertBulk {
	return u.Update(func(s *RentalOptionUpsert) {
		s.SetRentalID(v)
	})
}

// UpdateRentalID sets the "rental_id" field to the value that was provided on create.
func (u *RentalOptionUpsertBulk) UpdateRentalID() *RentalOptionUpsertBulk {
	return u.Update(func(s *RentalOptionUpsert) {
		s.UpdateRentalID()
	})
}

// SetOptionID sets the "option_id" field.
func (u *RentalOptionUpsertBulk) SetOptionID(v string) *RentalOptionUpsertBulk {
	return u.Update(func(s *RentalOptionUpsert) {
		s.SetOptionID(v)
	})
}

// UpdateOptionID sets the "option_id" field to the value that was provided on create.
func (u *RentalOptionUpsertBulk) UpdateOptionID() *RentalOptionUpsertBulk {
	return u.Update(func(s *RentalOptionUpsert) {
		s.UpdateOptionID()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *RentalOptionUpsertBulk) SetTenantID(v string) *RentalOptionUpsertBulk {
	return u.Update(func(s *RentalOptionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *RentalOptionUpsertBulk) UpdateTenantID() *RentalOptionUpsertBulk {
	return u.Update(func(s *RentalOptionUpsert) {
		s.UpdateTenantID()
	})
}

// Exec executes the query.
func (u *RentalOptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RentalOptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RentalOptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RentalOptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
