// Code generated by ent, DO NOT EDIT.

package rentaloption

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jp-ryuji/go-sample/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldContainsFold(FieldID, id))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEQ(FieldCount, v))
}

// RentalID applies equality check predicate on the "rental_id" field. It's identical to RentalIDEQ.
func RentalID(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEQ(FieldRentalID, v))
}

// OptionID applies equality check predicate on the "option_id" field. It's identical to OptionIDEQ.
func OptionID(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEQ(FieldOptionID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEQ(FieldTenantID, v))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldLTE(FieldCount, v))
}

// RentalIDEQ applies the EQ predicate on the "rental_id" field.
func RentalIDEQ(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEQ(FieldRentalID, v))
}

// RentalIDNEQ applies the NEQ predicate on the "rental_id" field.
func RentalIDNEQ(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldNEQ(FieldRentalID, v))
}

// RentalIDIn applies the In predicate on the "rental_id" field.
func RentalIDIn(vs ...string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldIn(FieldRentalID, vs...))
}

// RentalIDNotIn applies the NotIn predicate on the "rental_id" field.
func RentalIDNotIn(vs ...string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldNotIn(FieldRentalID, vs...))
}

// RentalIDGT applies the GT predicate on the "rental_id" field.
func RentalIDGT(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldGT(FieldRentalID, v))
}

// RentalIDGTE applies the GTE predicate on the "rental_id" field.
func RentalIDGTE(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldGTE(FieldRentalID, v))
}

// RentalIDLT applies the LT predicate on the "rental_id" field.
func RentalIDLT(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldLT(FieldRentalID, v))
}

// RentalIDLTE applies the LTE predicate on the "rental_id" field.
func RentalIDLTE(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldLTE(FieldRentalID, v))
}

// RentalIDContains applies the Contains predicate on the "rental_id" field.
func RentalIDContains(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldContains(FieldRentalID, v))
}

// RentalIDHasPrefix applies the HasPrefix predicate on the "rental_id" field.
func RentalIDHasPrefix(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldHasPrefix(FieldRentalID, v))
}

// RentalIDHasSuffix applies the HasSuffix predicate on the "rental_id" field.
func RentalIDHasSuffix(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldHasSuffix(FieldRentalID, v))
}

// RentalIDEqualFold applies the EqualFold predicate on the "rental_id" field.
func RentalIDEqualFold(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEqualFold(FieldRentalID, v))
}

// RentalIDContainsFold applies the ContainsFold predicate on the "rental_id" field.
func RentalIDContainsFold(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldContainsFold(FieldRentalID, v))
}

// OptionIDEQ applies the EQ predicate on the "option_id" field.
func OptionIDEQ(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEQ(FieldOptionID, v))
}

// OptionIDNEQ applies the NEQ predicate on the "option_id" field.
func OptionIDNEQ(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldNEQ(FieldOptionID, v))
}

// OptionIDIn applies the In predicate on the "option_id" field.
func OptionIDIn(vs ...string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldIn(FieldOptionID, vs...))
}

// OptionIDNotIn applies the NotIn predicate on the "option_id" field.
func OptionIDNotIn(vs ...string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldNotIn(FieldOptionID, vs...))
}

// OptionIDGT applies the GT predicate on the "option_id" field.
func OptionIDGT(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldGT(FieldOptionID, v))
}

// OptionIDGTE applies the GTE predicate on the "option_id" field.
func OptionIDGTE(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldGTE(FieldOptionID, v))
}

// OptionIDLT applies the LT predicate on the "option_id" field.
func OptionIDLT(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldLT(FieldOptionID, v))
}

// OptionIDLTE applies the LTE predicate on the "option_id" field.
func OptionIDLTE(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldLTE(FieldOptionID, v))
}

// OptionIDContains applies the Contains predicate on the "option_id" field.
func OptionIDContains(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldContains(FieldOptionID, v))
}

// OptionIDHasPrefix applies the HasPrefix predicate on the "option_id" field.
func OptionIDHasPrefix(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldHasPrefix(FieldOptionID, v))
}

// OptionIDHasSuffix applies the HasSuffix predicate on the "option_id" field.
func OptionIDHasSuffix(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldHasSuffix(FieldOptionID, v))
}

// OptionIDEqualFold applies the EqualFold predicate on the "option_id" field.
func OptionIDEqualFold(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEqualFold(FieldOptionID, v))
}

// OptionIDContainsFold applies the ContainsFold predicate on the "option_id" field.
func OptionIDContainsFold(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldContainsFold(FieldOptionID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.RentalOption {
	return predicate.RentalOption(sql.FieldContainsFold(FieldTenantID, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.RentalOption {
	return predicate.RentalOption(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.RentalOption {
	return predicate.RentalOption(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRental applies the HasEdge predicate on the "rental" edge.
func HasRental() predicate.RentalOption {
	return predicate.RentalOption(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RentalTable, RentalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRentalWith applies the HasEdge predicate on the "rental" edge with a given conditions (other predicates).
func HasRentalWith(preds ...predicate.Rental) predicate.RentalOption {
	return predicate.RentalOption(func(s *sql.Selector) {
		step := newRentalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOption applies the HasEdge predicate on the "option" edge.
func HasOption() predicate.RentalOption {
	return predicate.RentalOption(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OptionTable, OptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOptionWith applies the HasEdge predicate on the "option" edge with a given conditions (other predicates).
func HasOptionWith(preds ...predicate.CarOption) predicate.RentalOption {
	return predicate.RentalOption(func(s *sql.Selector) {
		step := newOptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RentalOption) predicate.RentalOption {
	return predicate.RentalOption(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RentalOption) predicate.RentalOption {
	return predicate.RentalOption(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RentalOption) predicate.RentalOption {
	return predicate.RentalOption(sql.NotPredicates(p))
}
