// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/individual"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/renter"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/tenant"
)

// IndividualCreate is the builder for creating a Individual entity.
type IndividualCreate struct {
	config
	mutation *IndividualMutation
	hooks    []Hook
}

// SetRenterID sets the "renter_id" field.
func (_c *IndividualCreate) SetRenterID(v string) *IndividualCreate {
	_c.mutation.SetRenterID(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *IndividualCreate) SetTenantID(v string) *IndividualCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *IndividualCreate) SetEmail(v string) *IndividualCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetFirstName sets the "first_name" field.
func (_c *IndividualCreate) SetFirstName(v string) *IndividualCreate {
	_c.mutation.SetFirstName(v)
	return _c
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_c *IndividualCreate) SetNillableFirstName(v *string) *IndividualCreate {
	if v != nil {
		_c.SetFirstName(*v)
	}
	return _c
}

// SetLastName sets the "last_name" field.
func (_c *IndividualCreate) SetLastName(v string) *IndividualCreate {
	_c.mutation.SetLastName(v)
	return _c
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_c *IndividualCreate) SetNillableLastName(v *string) *IndividualCreate {
	if v != nil {
		_c.SetLastName(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IndividualCreate) SetCreatedAt(v time.Time) *IndividualCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IndividualCreate) SetNillableCreatedAt(v *time.Time) *IndividualCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IndividualCreate) SetUpdatedAt(v time.Time) *IndividualCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IndividualCreate) SetNillableUpdatedAt(v *time.Time) *IndividualCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *IndividualCreate) SetDeletedAt(v time.Time) *IndividualCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *IndividualCreate) SetNillableDeletedAt(v *time.Time) *IndividualCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IndividualCreate) SetID(v string) *IndividualCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *IndividualCreate) SetTenant(v *Tenant) *IndividualCreate {
	return _c.SetTenantID(v.ID)
}

// SetRenter sets the "renter" edge to the Renter entity.
func (_c *IndividualCreate) SetRenter(v *Renter) *IndividualCreate {
	return _c.SetRenterID(v.ID)
}

// Mutation returns the IndividualMutation object of the builder.
func (_c *IndividualCreate) Mutation() *IndividualMutation {
	return _c.mutation
}

// Save creates the Individual in the database.
func (_c *IndividualCreate) Save(ctx context.Context) (*Individual, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IndividualCreate) SaveX(ctx context.Context) *Individual {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IndividualCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IndividualCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IndividualCreate) check() error {
	if _, ok := _c.mutation.RenterID(); !ok {
		return &ValidationError{Name: "renter_id", err: errors.New(`entgen: missing required field "Individual.renter_id"`)}
	}
	if v, ok := _c.mutation.RenterID(); ok {
		if err := individual.RenterIDValidator(v); err != nil {
			return &ValidationError{Name: "renter_id", err: fmt.Errorf(`entgen: validator failed for field "Individual.renter_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`entgen: missing required field "Individual.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := individual.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`entgen: validator failed for field "Individual.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`entgen: missing required field "Individual.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := individual.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`entgen: validator failed for field "Individual.email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FirstName(); ok {
		if err := individual.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`entgen: validator failed for field "Individual.first_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastName(); ok {
		if err := individual.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`entgen: validator failed for field "Individual.last_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := individual.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`entgen: validator failed for field "Individual.id": %w`, err)}
		}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`entgen: missing required edge "Individual.tenant"`)}
	}
	if len(_c.mutation.RenterIDs()) == 0 {
		return &ValidationError{Name: "renter", err: errors.New(`entgen: missing required edge "Individual.renter"`)}
	}
	return nil
}

func (_c *IndividualCreate) sqlSave(ctx context.Context) (*Individual, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Individual.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IndividualCreate) createSpec() (*Individual, *sqlgraph.CreateSpec) {
	var (
		_node = &Individual{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(individual.Table, sqlgraph.NewFieldSpec(individual.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(individual.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.FirstName(); ok {
		_spec.SetField(individual.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := _c.mutation.LastName(); ok {
		_spec.SetField(individual.FieldLastName, field.TypeString, value)
		_node.LastName = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(individual.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(individual.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(individual.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   individual.TenantTable,
			Columns: []string{individual.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RenterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   individual.RenterTable,
			Columns: []string{individual.RenterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(renter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RenterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IndividualCreateBulk is the builder for creating many Individual entities in bulk.
type IndividualCreateBulk struct {
	config
	err      error
	builders []*IndividualCreate
}

// Save creates the Individual entities in the database.
func (_c *IndividualCreateBulk) Save(ctx context.Context) ([]*Individual, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Individual, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IndividualMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IndividualCreateBulk) SaveX(ctx context.Context) []*Individual {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IndividualCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IndividualCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
