// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/individual"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/predicate"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/renter"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/tenant"
)

// IndividualUpdate is the builder for updating Individual entities.
type IndividualUpdate struct {
	config
	hooks    []Hook
	mutation *IndividualMutation
}

// Where appends a list predicates to the IndividualUpdate builder.
func (_u *IndividualUpdate) Where(ps ...predicate.Individual) *IndividualUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRenterID sets the "renter_id" field.
func (_u *IndividualUpdate) SetRenterID(v string) *IndividualUpdate {
	_u.mutation.SetRenterID(v)
	return _u
}

// SetNillableRenterID sets the "renter_id" field if the given value is not nil.
func (_u *IndividualUpdate) SetNillableRenterID(v *string) *IndividualUpdate {
	if v != nil {
		_u.SetRenterID(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *IndividualUpdate) SetTenantID(v string) *IndividualUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *IndividualUpdate) SetNillableTenantID(v *string) *IndividualUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *IndividualUpdate) SetEmail(v string) *IndividualUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *IndividualUpdate) SetNillableEmail(v *string) *IndividualUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *IndividualUpdate) SetFirstName(v string) *IndividualUpdate {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *IndividualUpdate) SetNillableFirstName(v *string) *IndividualUpdate {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// ClearFirstName clears the value of the "first_name" field.
func (_u *IndividualUpdate) ClearFirstName() *IndividualUpdate {
	_u.mutation.ClearFirstName()
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *IndividualUpdate) SetLastName(v string) *IndividualUpdate {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *IndividualUpdate) SetNillableLastName(v *string) *IndividualUpdate {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// ClearLastName clears the value of the "last_name" field.
func (_u *IndividualUpdate) ClearLastName() *IndividualUpdate {
	_u.mutation.ClearLastName()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IndividualUpdate) SetCreatedAt(v time.Time) *IndividualUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IndividualUpdate) SetNillableCreatedAt(v *time.Time) *IndividualUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *IndividualUpdate) ClearCreatedAt() *IndividualUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IndividualUpdate) SetUpdatedAt(v time.Time) *IndividualUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *IndividualUpdate) SetNillableUpdatedAt(v *time.Time) *IndividualUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *IndividualUpdate) ClearUpdatedAt() *IndividualUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *IndividualUpdate) SetDeletedAt(v time.Time) *IndividualUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *IndividualUpdate) SetNillableDeletedAt(v *time.Time) *IndividualUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *IndividualUpdate) ClearDeletedAt() *IndividualUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *IndividualUpdate) SetTenant(v *Tenant) *IndividualUpdate {
	return _u.SetTenantID(v.ID)
}

// SetRenter sets the "renter" edge to the Renter entity.
func (_u *IndividualUpdate) SetRenter(v *Renter) *IndividualUpdate {
	return _u.SetRenterID(v.ID)
}

// Mutation returns the IndividualMutation object of the builder.
func (_u *IndividualUpdate) Mutation() *IndividualMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *IndividualUpdate) ClearTenant() *IndividualUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearRenter clears the "renter" edge to the Renter entity.
func (_u *IndividualUpdate) ClearRenter() *IndividualUpdate {
	_u.mutation.ClearRenter()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IndividualUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IndividualUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IndividualUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IndividualUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IndividualUpdate) check() error {
	if v, ok := _u.mutation.RenterID(); ok {
		if err := individual.RenterIDValidator(v); err != nil {
			return &ValidationError{Name: "renter_id", err: fmt.Errorf(`entgen: validator failed for field "Individual.renter_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TenantID(); ok {
		if err := individual.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`entgen: validator failed for field "Individual.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := individual.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`entgen: validator failed for field "Individual.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirstName(); ok {
		if err := individual.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`entgen: validator failed for field "Individual.first_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastName(); ok {
		if err := individual.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`entgen: validator failed for field "Individual.last_name": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`entgen: clearing a required unique edge "Individual.tenant"`)
	}
	if _u.mutation.RenterCleared() && len(_u.mutation.RenterIDs()) > 0 {
		return errors.New(`entgen: clearing a required unique edge "Individual.renter"`)
	}
	return nil
}

func (_u *IndividualUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(individual.Table, individual.Columns, sqlgraph.NewFieldSpec(individual.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(individual.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(individual.FieldFirstName, field.TypeString, value)
	}
	if _u.mutation.FirstNameCleared() {
		_spec.ClearField(individual.FieldFirstName, field.TypeString)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(individual.FieldLastName, field.TypeString, value)
	}
	if _u.mutation.LastNameCleared() {
		_spec.ClearField(individual.FieldLastName, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(individual.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(individual.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(individual.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(individual.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(individual.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(individual.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   individual.TenantTable,
			Columns: []string{individual.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   individual.TenantTable,
			Columns: []string{individual.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RenterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   individual.RenterTable,
			Columns: []string{individual.RenterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(renter.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RenterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   individual.RenterTable,
			Columns: []string{individual.RenterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(renter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{individual.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IndividualUpdateOne is the builder for updating a single Individual entity.
type IndividualUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IndividualMutation
}

// SetRenterID sets the "renter_id" field.
func (_u *IndividualUpdateOne) SetRenterID(v string) *IndividualUpdateOne {
	_u.mutation.SetRenterID(v)
	return _u
}

// SetNillableRenterID sets the "renter_id" field if the given value is not nil.
func (_u *IndividualUpdateOne) SetNillableRenterID(v *string) *IndividualUpdateOne {
	if v != nil {
		_u.SetRenterID(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *IndividualUpdateOne) SetTenantID(v string) *IndividualUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *IndividualUpdateOne) SetNillableTenantID(v *string) *IndividualUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *IndividualUpdateOne) SetEmail(v string) *IndividualUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *IndividualUpdateOne) SetNillableEmail(v *string) *IndividualUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *IndividualUpdateOne) SetFirstName(v string) *IndividualUpdateOne {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *IndividualUpdateOne) SetNillableFirstName(v *string) *IndividualUpdateOne {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// ClearFirstName clears the value of the "first_name" field.
func (_u *IndividualUpdateOne) ClearFirstName() *IndividualUpdateOne {
	_u.mutation.ClearFirstName()
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *IndividualUpdateOne) SetLastName(v string) *IndividualUpdateOne {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *IndividualUpdateOne) SetNillableLastName(v *string) *IndividualUpdateOne {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// ClearLastName clears the value of the "last_name" field.
func (_u *IndividualUpdateOne) ClearLastName() *IndividualUpdateOne {
	_u.mutation.ClearLastName()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IndividualUpdateOne) SetCreatedAt(v time.Time) *IndividualUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IndividualUpdateOne) SetNillableCreatedAt(v *time.Time) *IndividualUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *IndividualUpdateOne) ClearCreatedAt() *IndividualUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IndividualUpdateOne) SetUpdatedAt(v time.Time) *IndividualUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *IndividualUpdateOne) SetNillableUpdatedAt(v *time.Time) *IndividualUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *IndividualUpdateOne) ClearUpdatedAt() *IndividualUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *IndividualUpdateOne) SetDeletedAt(v time.Time) *IndividualUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *IndividualUpdateOne) SetNillableDeletedAt(v *time.Time) *IndividualUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *IndividualUpdateOne) ClearDeletedAt() *IndividualUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *IndividualUpdateOne) SetTenant(v *Tenant) *IndividualUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetRenter sets the "renter" edge to the Renter entity.
func (_u *IndividualUpdateOne) SetRenter(v *Renter) *IndividualUpdateOne {
	return _u.SetRenterID(v.ID)
}

// Mutation returns the IndividualMutation object of the builder.
func (_u *IndividualUpdateOne) Mutation() *IndividualMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *IndividualUpdateOne) ClearTenant() *IndividualUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearRenter clears the "renter" edge to the Renter entity.
func (_u *IndividualUpdateOne) ClearRenter() *IndividualUpdateOne {
	_u.mutation.ClearRenter()
	return _u
}

// Where appends a list predicates to the IndividualUpdate builder.
func (_u *IndividualUpdateOne) Where(ps ...predicate.Individual) *IndividualUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IndividualUpdateOne) Select(field string, fields ...string) *IndividualUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Individual entity.
func (_u *IndividualUpdateOne) Save(ctx context.Context) (*Individual, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IndividualUpdateOne) SaveX(ctx context.Context) *Individual {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IndividualUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IndividualUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IndividualUpdateOne) check() error {
	if v, ok := _u.mutation.RenterID(); ok {
		if err := individual.RenterIDValidator(v); err != nil {
			return &ValidationError{Name: "renter_id", err: fmt.Errorf(`entgen: validator failed for field "Individual.renter_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TenantID(); ok {
		if err := individual.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`entgen: validator failed for field "Individual.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := individual.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`entgen: validator failed for field "Individual.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirstName(); ok {
		if err := individual.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`entgen: validator failed for field "Individual.first_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastName(); ok {
		if err := individual.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`entgen: validator failed for field "Individual.last_name": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`entgen: clearing a required unique edge "Individual.tenant"`)
	}
	if _u.mutation.RenterCleared() && len(_u.mutation.RenterIDs()) > 0 {
		return errors.New(`entgen: clearing a required unique edge "Individual.renter"`)
	}
	return nil
}

func (_u *IndividualUpdateOne) sqlSave(ctx context.Context) (_node *Individual, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(individual.Table, individual.Columns, sqlgraph.NewFieldSpec(individual.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entgen: missing "Individual.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, individual.FieldID)
		for _, f := range fields {
			if !individual.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entgen: invalid field %q for query", f)}
			}
			if f != individual.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(individual.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(individual.FieldFirstName, field.TypeString, value)
	}
	if _u.mutation.FirstNameCleared() {
		_spec.ClearField(individual.FieldFirstName, field.TypeString)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(individual.FieldLastName, field.TypeString, value)
	}
	if _u.mutation.LastNameCleared() {
		_spec.ClearField(individual.FieldLastName, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(individual.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(individual.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(individual.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(individual.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(individual.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(individual.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   individual.TenantTable,
			Columns: []string{individual.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   individual.TenantTable,
			Columns: []string{individual.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RenterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   individual.RenterTable,
			Columns: []string{individual.RenterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(renter.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RenterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   individual.RenterTable,
			Columns: []string{individual.RenterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(renter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Individual{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{individual.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
