// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/car"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/predicate"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/rental"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/rentaloption"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/renter"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/tenant"
)

// RentalQuery is the builder for querying Rental entities.
type RentalQuery struct {
	config
	ctx               *QueryContext
	order             []rental.OrderOption
	inters            []Interceptor
	predicates        []predicate.Rental
	withTenant        *TenantQuery
	withCar           *CarQuery
	withRenter        *RenterQuery
	withRentalOptions *RentalOptionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RentalQuery builder.
func (_q *RentalQuery) Where(ps ...predicate.Rental) *RentalQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RentalQuery) Limit(limit int) *RentalQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RentalQuery) Offset(offset int) *RentalQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RentalQuery) Unique(unique bool) *RentalQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RentalQuery) Order(o ...rental.OrderOption) *RentalQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTenant chains the current query on the "tenant" edge.
func (_q *RentalQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rental.Table, rental.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rental.TenantTable, rental.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCar chains the current query on the "car" edge.
func (_q *RentalQuery) QueryCar() *CarQuery {
	query := (&CarClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rental.Table, rental.FieldID, selector),
			sqlgraph.To(car.Table, car.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rental.CarTable, rental.CarColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRenter chains the current query on the "renter" edge.
func (_q *RentalQuery) QueryRenter() *RenterQuery {
	query := (&RenterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rental.Table, rental.FieldID, selector),
			sqlgraph.To(renter.Table, renter.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rental.RenterTable, rental.RenterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRentalOptions chains the current query on the "rental_options" edge.
func (_q *RentalQuery) QueryRentalOptions() *RentalOptionQuery {
	query := (&RentalOptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rental.Table, rental.FieldID, selector),
			sqlgraph.To(rentaloption.Table, rentaloption.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rental.RentalOptionsTable, rental.RentalOptionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Rental entity from the query.
// Returns a *NotFoundError when no Rental was found.
func (_q *RentalQuery) First(ctx context.Context) (*Rental, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rental.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RentalQuery) FirstX(ctx context.Context) *Rental {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Rental ID from the query.
// Returns a *NotFoundError when no Rental ID was found.
func (_q *RentalQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rental.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RentalQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Rental entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Rental entity is found.
// Returns a *NotFoundError when no Rental entities are found.
func (_q *RentalQuery) Only(ctx context.Context) (*Rental, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rental.Label}
	default:
		return nil, &NotSingularError{rental.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RentalQuery) OnlyX(ctx context.Context) *Rental {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Rental ID in the query.
// Returns a *NotSingularError when more than one Rental ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RentalQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rental.Label}
	default:
		err = &NotSingularError{rental.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RentalQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Rentals.
func (_q *RentalQuery) All(ctx context.Context) ([]*Rental, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Rental, *RentalQuery]()
	return withInterceptors[[]*Rental](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RentalQuery) AllX(ctx context.Context) []*Rental {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Rental IDs.
func (_q *RentalQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(rental.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RentalQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RentalQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RentalQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RentalQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RentalQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entgen: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RentalQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RentalQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RentalQuery) Clone() *RentalQuery {
	if _q == nil {
		return nil
	}
	return &RentalQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]rental.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.Rental{}, _q.predicates...),
		withTenant:        _q.withTenant.Clone(),
		withCar:           _q.withCar.Clone(),
		withRenter:        _q.withRenter.Clone(),
		withRentalOptions: _q.withRentalOptions.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RentalQuery) WithTenant(opts ...func(*TenantQuery)) *RentalQuery {
	query := (&TenantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenant = query
	return _q
}

// WithCar tells the query-builder to eager-load the nodes that are connected to
// the "car" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RentalQuery) WithCar(opts ...func(*CarQuery)) *RentalQuery {
	query := (&CarClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCar = query
	return _q
}

// WithRenter tells the query-builder to eager-load the nodes that are connected to
// the "renter" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RentalQuery) WithRenter(opts ...func(*RenterQuery)) *RentalQuery {
	query := (&RenterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRenter = query
	return _q
}

// WithRentalOptions tells the query-builder to eager-load the nodes that are connected to
// the "rental_options" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RentalQuery) WithRentalOptions(opts ...func(*RentalOptionQuery)) *RentalQuery {
	query := (&RentalOptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRentalOptions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Rental.Query().
//		GroupBy(rental.FieldTenantID).
//		Aggregate(entgen.Count()).
//		Scan(ctx, &v)
func (_q *RentalQuery) GroupBy(field string, fields ...string) *RentalGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RentalGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = rental.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.Rental.Query().
//		Select(rental.FieldTenantID).
//		Scan(ctx, &v)
func (_q *RentalQuery) Select(fields ...string) *RentalSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RentalSelect{RentalQuery: _q}
	sbuild.label = rental.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RentalSelect configured with the given aggregations.
func (_q *RentalQuery) Aggregate(fns ...AggregateFunc) *RentalSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RentalQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("entgen: uninitialized interceptor (forgotten import entgen/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !rental.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entgen: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RentalQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Rental, error) {
	var (
		nodes       = []*Rental{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withTenant != nil,
			_q.withCar != nil,
			_q.withRenter != nil,
			_q.withRentalOptions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Rental).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Rental{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTenant; query != nil {
		if err := _q.loadTenant(ctx, query, nodes, nil,
			func(n *Rental, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCar; query != nil {
		if err := _q.loadCar(ctx, query, nodes, nil,
			func(n *Rental, e *Car) { n.Edges.Car = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRenter; query != nil {
		if err := _q.loadRenter(ctx, query, nodes, nil,
			func(n *Rental, e *Renter) { n.Edges.Renter = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRentalOptions; query != nil {
		if err := _q.loadRentalOptions(ctx, query, nodes,
			func(n *Rental) { n.Edges.RentalOptions = []*RentalOption{} },
			func(n *Rental, e *RentalOption) { n.Edges.RentalOptions = append(n.Edges.RentalOptions, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RentalQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*Rental, init func(*Rental), assign func(*Rental, *Tenant)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Rental)
	for i := range nodes {
		fk := nodes[i].TenantID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RentalQuery) loadCar(ctx context.Context, query *CarQuery, nodes []*Rental, init func(*Rental), assign func(*Rental, *Car)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Rental)
	for i := range nodes {
		fk := nodes[i].CarID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(car.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "car_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RentalQuery) loadRenter(ctx context.Context, query *RenterQuery, nodes []*Rental, init func(*Rental), assign func(*Rental, *Renter)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Rental)
	for i := range nodes {
		fk := nodes[i].RenterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(renter.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "renter_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RentalQuery) loadRentalOptions(ctx context.Context, query *RentalOptionQuery, nodes []*Rental, init func(*Rental), assign func(*Rental, *RentalOption)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Rental)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rentaloption.FieldRentalID)
	}
	query.Where(predicate.RentalOption(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rental.RentalOptionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RentalID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "rental_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *RentalQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RentalQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rental.Table, rental.Columns, sqlgraph.NewFieldSpec(rental.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rental.FieldID)
		for i := range fields {
			if fields[i] != rental.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTenant != nil {
			_spec.Node.AddColumnOnce(rental.FieldTenantID)
		}
		if _q.withCar != nil {
			_spec.Node.AddColumnOnce(rental.FieldCarID)
		}
		if _q.withRenter != nil {
			_spec.Node.AddColumnOnce(rental.FieldRenterID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RentalQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(rental.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = rental.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RentalGroupBy is the group-by builder for Rental entities.
type RentalGroupBy struct {
	selector
	build *RentalQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RentalGroupBy) Aggregate(fns ...AggregateFunc) *RentalGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RentalGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RentalQuery, *RentalGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RentalGroupBy) sqlScan(ctx context.Context, root *RentalQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RentalSelect is the builder for selecting fields of Rental entities.
type RentalSelect struct {
	*RentalQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RentalSelect) Aggregate(fns ...AggregateFunc) *RentalSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RentalSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RentalQuery, *RentalSelect](ctx, _s.RentalQuery, _s, _s.inters, v)
}

func (_s *RentalSelect) sqlScan(ctx context.Context, root *RentalQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
