// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/predicate"
	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/entgen/rentaloption"
)

// RentalOptionDelete is the builder for deleting a RentalOption entity.
type RentalOptionDelete struct {
	config
	hooks    []Hook
	mutation *RentalOptionMutation
}

// Where appends a list predicates to the RentalOptionDelete builder.
func (_d *RentalOptionDelete) Where(ps ...predicate.RentalOption) *RentalOptionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RentalOptionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RentalOptionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RentalOptionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rentaloption.Table, sqlgraph.NewFieldSpec(rentaloption.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RentalOptionDeleteOne is the builder for deleting a single RentalOption entity.
type RentalOptionDeleteOne struct {
	_d *RentalOptionDelete
}

// Where appends a list predicates to the RentalOptionDelete builder.
func (_d *RentalOptionDeleteOne) Where(ps ...predicate.RentalOption) *RentalOptionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RentalOptionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rentaloption.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RentalOptionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
