// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jp-ryuji/go-arch-patterns/internal/infrastructure/postgres/entgen/car"
	"github.com/jp-ryuji/go-arch-patterns/internal/infrastructure/postgres/entgen/caroption"
	"github.com/jp-ryuji/go-arch-patterns/internal/infrastructure/postgres/entgen/company"
	"github.com/jp-ryuji/go-arch-patterns/internal/infrastructure/postgres/entgen/individual"
	"github.com/jp-ryuji/go-arch-patterns/internal/infrastructure/postgres/entgen/predicate"
	"github.com/jp-ryuji/go-arch-patterns/internal/infrastructure/postgres/entgen/rental"
	"github.com/jp-ryuji/go-arch-patterns/internal/infrastructure/postgres/entgen/rentaloption"
	"github.com/jp-ryuji/go-arch-patterns/internal/infrastructure/postgres/entgen/renter"
	"github.com/jp-ryuji/go-arch-patterns/internal/infrastructure/postgres/entgen/tenant"
)

// TenantQuery is the builder for querying Tenant entities.
type TenantQuery struct {
	config
	ctx               *QueryContext
	order             []tenant.OrderOption
	inters            []Interceptor
	predicates        []predicate.Tenant
	withCars          *CarQuery
	withCompanies     *CompanyQuery
	withIndividuals   *IndividualQuery
	withOptions       *CarOptionQuery
	withRentalOptions *RentalOptionQuery
	withRentals       *RentalQuery
	withRenters       *RenterQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TenantQuery builder.
func (_q *TenantQuery) Where(ps ...predicate.Tenant) *TenantQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TenantQuery) Limit(limit int) *TenantQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TenantQuery) Offset(offset int) *TenantQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TenantQuery) Unique(unique bool) *TenantQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TenantQuery) Order(o ...tenant.OrderOption) *TenantQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCars chains the current query on the "cars" edge.
func (_q *TenantQuery) QueryCars() *CarQuery {
	query := (&CarClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(car.Table, car.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.CarsTable, tenant.CarsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCompanies chains the current query on the "companies" edge.
func (_q *TenantQuery) QueryCompanies() *CompanyQuery {
	query := (&CompanyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(company.Table, company.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.CompaniesTable, tenant.CompaniesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryIndividuals chains the current query on the "individuals" edge.
func (_q *TenantQuery) QueryIndividuals() *IndividualQuery {
	query := (&IndividualClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(individual.Table, individual.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.IndividualsTable, tenant.IndividualsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOptions chains the current query on the "options" edge.
func (_q *TenantQuery) QueryOptions() *CarOptionQuery {
	query := (&CarOptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(caroption.Table, caroption.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.OptionsTable, tenant.OptionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRentalOptions chains the current query on the "rental_options" edge.
func (_q *TenantQuery) QueryRentalOptions() *RentalOptionQuery {
	query := (&RentalOptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(rentaloption.Table, rentaloption.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.RentalOptionsTable, tenant.RentalOptionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRentals chains the current query on the "rentals" edge.
func (_q *TenantQuery) QueryRentals() *RentalQuery {
	query := (&RentalClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(rental.Table, rental.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.RentalsTable, tenant.RentalsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRenters chains the current query on the "renters" edge.
func (_q *TenantQuery) QueryRenters() *RenterQuery {
	query := (&RenterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(renter.Table, renter.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.RentersTable, tenant.RentersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Tenant entity from the query.
// Returns a *NotFoundError when no Tenant was found.
func (_q *TenantQuery) First(ctx context.Context) (*Tenant, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tenant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TenantQuery) FirstX(ctx context.Context) *Tenant {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Tenant ID from the query.
// Returns a *NotFoundError when no Tenant ID was found.
func (_q *TenantQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tenant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TenantQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Tenant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Tenant entity is found.
// Returns a *NotFoundError when no Tenant entities are found.
func (_q *TenantQuery) Only(ctx context.Context) (*Tenant, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tenant.Label}
	default:
		return nil, &NotSingularError{tenant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TenantQuery) OnlyX(ctx context.Context) *Tenant {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Tenant ID in the query.
// Returns a *NotSingularError when more than one Tenant ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TenantQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tenant.Label}
	default:
		err = &NotSingularError{tenant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TenantQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Tenants.
func (_q *TenantQuery) All(ctx context.Context) ([]*Tenant, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Tenant, *TenantQuery]()
	return withInterceptors[[]*Tenant](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TenantQuery) AllX(ctx context.Context) []*Tenant {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Tenant IDs.
func (_q *TenantQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(tenant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TenantQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TenantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TenantQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TenantQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TenantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entgen: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TenantQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TenantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TenantQuery) Clone() *TenantQuery {
	if _q == nil {
		return nil
	}
	return &TenantQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]tenant.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.Tenant{}, _q.predicates...),
		withCars:          _q.withCars.Clone(),
		withCompanies:     _q.withCompanies.Clone(),
		withIndividuals:   _q.withIndividuals.Clone(),
		withOptions:       _q.withOptions.Clone(),
		withRentalOptions: _q.withRentalOptions.Clone(),
		withRentals:       _q.withRentals.Clone(),
		withRenters:       _q.withRenters.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCars tells the query-builder to eager-load the nodes that are connected to
// the "cars" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithCars(opts ...func(*CarQuery)) *TenantQuery {
	query := (&CarClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCars = query
	return _q
}

// WithCompanies tells the query-builder to eager-load the nodes that are connected to
// the "companies" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithCompanies(opts ...func(*CompanyQuery)) *TenantQuery {
	query := (&CompanyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCompanies = query
	return _q
}

// WithIndividuals tells the query-builder to eager-load the nodes that are connected to
// the "individuals" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithIndividuals(opts ...func(*IndividualQuery)) *TenantQuery {
	query := (&IndividualClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withIndividuals = query
	return _q
}

// WithOptions tells the query-builder to eager-load the nodes that are connected to
// the "options" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithOptions(opts ...func(*CarOptionQuery)) *TenantQuery {
	query := (&CarOptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOptions = query
	return _q
}

// WithRentalOptions tells the query-builder to eager-load the nodes that are connected to
// the "rental_options" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithRentalOptions(opts ...func(*RentalOptionQuery)) *TenantQuery {
	query := (&RentalOptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRentalOptions = query
	return _q
}

// WithRentals tells the query-builder to eager-load the nodes that are connected to
// the "rentals" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithRentals(opts ...func(*RentalQuery)) *TenantQuery {
	query := (&RentalClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRentals = query
	return _q
}

// WithRenters tells the query-builder to eager-load the nodes that are connected to
// the "renters" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithRenters(opts ...func(*RenterQuery)) *TenantQuery {
	query := (&RenterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRenters = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Tenant.Query().
//		GroupBy(tenant.FieldCode).
//		Aggregate(entgen.Count()).
//		Scan(ctx, &v)
func (_q *TenantQuery) GroupBy(field string, fields ...string) *TenantGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TenantGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = tenant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//	}
//
//	client.Tenant.Query().
//		Select(tenant.FieldCode).
//		Scan(ctx, &v)
func (_q *TenantQuery) Select(fields ...string) *TenantSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TenantSelect{TenantQuery: _q}
	sbuild.label = tenant.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TenantSelect configured with the given aggregations.
func (_q *TenantQuery) Aggregate(fns ...AggregateFunc) *TenantSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TenantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("entgen: uninitialized interceptor (forgotten import entgen/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !tenant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entgen: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TenantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Tenant, error) {
	var (
		nodes       = []*Tenant{}
		_spec       = _q.querySpec()
		loadedTypes = [7]bool{
			_q.withCars != nil,
			_q.withCompanies != nil,
			_q.withIndividuals != nil,
			_q.withOptions != nil,
			_q.withRentalOptions != nil,
			_q.withRentals != nil,
			_q.withRenters != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Tenant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Tenant{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCars; query != nil {
		if err := _q.loadCars(ctx, query, nodes,
			func(n *Tenant) { n.Edges.Cars = []*Car{} },
			func(n *Tenant, e *Car) { n.Edges.Cars = append(n.Edges.Cars, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCompanies; query != nil {
		if err := _q.loadCompanies(ctx, query, nodes,
			func(n *Tenant) { n.Edges.Companies = []*Company{} },
			func(n *Tenant, e *Company) { n.Edges.Companies = append(n.Edges.Companies, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withIndividuals; query != nil {
		if err := _q.loadIndividuals(ctx, query, nodes,
			func(n *Tenant) { n.Edges.Individuals = []*Individual{} },
			func(n *Tenant, e *Individual) { n.Edges.Individuals = append(n.Edges.Individuals, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOptions; query != nil {
		if err := _q.loadOptions(ctx, query, nodes,
			func(n *Tenant) { n.Edges.Options = []*CarOption{} },
			func(n *Tenant, e *CarOption) { n.Edges.Options = append(n.Edges.Options, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRentalOptions; query != nil {
		if err := _q.loadRentalOptions(ctx, query, nodes,
			func(n *Tenant) { n.Edges.RentalOptions = []*RentalOption{} },
			func(n *Tenant, e *RentalOption) { n.Edges.RentalOptions = append(n.Edges.RentalOptions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRentals; query != nil {
		if err := _q.loadRentals(ctx, query, nodes,
			func(n *Tenant) { n.Edges.Rentals = []*Rental{} },
			func(n *Tenant, e *Rental) { n.Edges.Rentals = append(n.Edges.Rentals, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRenters; query != nil {
		if err := _q.loadRenters(ctx, query, nodes,
			func(n *Tenant) { n.Edges.Renters = []*Renter{} },
			func(n *Tenant, e *Renter) { n.Edges.Renters = append(n.Edges.Renters, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TenantQuery) loadCars(ctx context.Context, query *CarQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *Car)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(car.FieldTenantID)
	}
	query.Where(predicate.Car(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.CarsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadCompanies(ctx context.Context, query *CompanyQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *Company)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(company.FieldTenantID)
	}
	query.Where(predicate.Company(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.CompaniesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadIndividuals(ctx context.Context, query *IndividualQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *Individual)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(individual.FieldTenantID)
	}
	query.Where(predicate.Individual(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.IndividualsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadOptions(ctx context.Context, query *CarOptionQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *CarOption)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(caroption.FieldTenantID)
	}
	query.Where(predicate.CarOption(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.OptionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadRentalOptions(ctx context.Context, query *RentalOptionQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *RentalOption)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rentaloption.FieldTenantID)
	}
	query.Where(predicate.RentalOption(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.RentalOptionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadRentals(ctx context.Context, query *RentalQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *Rental)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rental.FieldTenantID)
	}
	query.Where(predicate.Rental(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.RentalsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadRenters(ctx context.Context, query *RenterQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *Renter)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(renter.FieldTenantID)
	}
	query.Where(predicate.Renter(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.RentersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *TenantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TenantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for i := range fields {
			if fields[i] != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TenantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(tenant.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = tenant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TenantGroupBy is the group-by builder for Tenant entities.
type TenantGroupBy struct {
	selector
	build *TenantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TenantGroupBy) Aggregate(fns ...AggregateFunc) *TenantGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TenantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TenantQuery, *TenantGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TenantGroupBy) sqlScan(ctx context.Context, root *TenantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TenantSelect is the builder for selecting fields of Tenant entities.
type TenantSelect struct {
	*TenantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TenantSelect) Aggregate(fns ...AggregateFunc) *TenantSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TenantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TenantQuery, *TenantSelect](ctx, _s.TenantQuery, _s, _s.inters, v)
}

func (_s *TenantSelect) sqlScan(ctx context.Context, root *TenantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
