// Code generated by ent, DO NOT EDIT.

package company

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jp-ryuji/go-sample/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldName, v))
}

// CompanySize applies equality check predicate on the "company_size" field. It's identical to CompanySizeEQ.
func CompanySize(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCompanySize, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldTenantID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldName, v))
}

// CompanySizeEQ applies the EQ predicate on the "company_size" field.
func CompanySizeEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldCompanySize, v))
}

// CompanySizeNEQ applies the NEQ predicate on the "company_size" field.
func CompanySizeNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldCompanySize, v))
}

// CompanySizeIn applies the In predicate on the "company_size" field.
func CompanySizeIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldCompanySize, vs...))
}

// CompanySizeNotIn applies the NotIn predicate on the "company_size" field.
func CompanySizeNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldCompanySize, vs...))
}

// CompanySizeGT applies the GT predicate on the "company_size" field.
func CompanySizeGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldCompanySize, v))
}

// CompanySizeGTE applies the GTE predicate on the "company_size" field.
func CompanySizeGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldCompanySize, v))
}

// CompanySizeLT applies the LT predicate on the "company_size" field.
func CompanySizeLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldCompanySize, v))
}

// CompanySizeLTE applies the LTE predicate on the "company_size" field.
func CompanySizeLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldCompanySize, v))
}

// CompanySizeContains applies the Contains predicate on the "company_size" field.
func CompanySizeContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldCompanySize, v))
}

// CompanySizeHasPrefix applies the HasPrefix predicate on the "company_size" field.
func CompanySizeHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldCompanySize, v))
}

// CompanySizeHasSuffix applies the HasSuffix predicate on the "company_size" field.
func CompanySizeHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldCompanySize, v))
}

// CompanySizeIsNil applies the IsNil predicate on the "company_size" field.
func CompanySizeIsNil() predicate.Company {
	return predicate.Company(sql.FieldIsNull(FieldCompanySize))
}

// CompanySizeNotNil applies the NotNil predicate on the "company_size" field.
func CompanySizeNotNil() predicate.Company {
	return predicate.Company(sql.FieldNotNull(FieldCompanySize))
}

// CompanySizeEqualFold applies the EqualFold predicate on the "company_size" field.
func CompanySizeEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldCompanySize, v))
}

// CompanySizeContainsFold applies the ContainsFold predicate on the "company_size" field.
func CompanySizeContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldCompanySize, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.Company {
	return predicate.Company(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.Company {
	return predicate.Company(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.Company {
	return predicate.Company(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.Company {
	return predicate.Company(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.Company {
	return predicate.Company(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.Company {
	return predicate.Company(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.Company {
	return predicate.Company(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.Company {
	return predicate.Company(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.Company {
	return predicate.Company(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.Company {
	return predicate.Company(sql.FieldContainsFold(FieldTenantID, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRenters applies the HasEdge predicate on the "renters" edge.
func HasRenters() predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, RentersTable, RentersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRentersWith applies the HasEdge predicate on the "renters" edge with a given conditions (other predicates).
func HasRentersWith(preds ...predicate.Renter) predicate.Company {
	return predicate.Company(func(s *sql.Selector) {
		step := newRentersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Company) predicate.Company {
	return predicate.Company(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Company) predicate.Company {
	return predicate.Company(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Company) predicate.Company {
	return predicate.Company(sql.NotPredicates(p))
}
