// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/jp-ryuji/go-sample/internal/infrastructure/postgres/dbmodel"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newRenter(db *gorm.DB, opts ...gen.DOOption) renter {
	_renter := renter{}

	_renter.renterDo.UseDB(db, opts...)
	_renter.renterDo.UseModel(&dbmodel.Renter{})

	tableName := _renter.renterDo.TableName()
	_renter.ALL = field.NewAsterisk(tableName)
	_renter.ID = field.NewString(tableName, "id")
	_renter.TenantID = field.NewString(tableName, "tenant_id")
	_renter.ConcreteRenterID = field.NewString(tableName, "concrete_renter_id")
	_renter.ConcreteRenterModel = field.NewString(tableName, "concrete_renter_model")
	_renter.CreatedAt = field.NewTime(tableName, "created_at")
	_renter.UpdatedAt = field.NewTime(tableName, "updated_at")
	_renter.DeletedAt = field.NewField(tableName, "deleted_at")

	_renter.fillFieldMap()

	return _renter
}

type renter struct {
	renterDo renterDo

	ALL                 field.Asterisk
	ID                  field.String
	TenantID            field.String
	ConcreteRenterID    field.String
	ConcreteRenterModel field.String
	CreatedAt           field.Time
	UpdatedAt           field.Time
	DeletedAt           field.Field

	fieldMap map[string]field.Expr
}

func (r renter) Table(newTableName string) *renter {
	r.renterDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r renter) As(alias string) *renter {
	r.renterDo.DO = *(r.renterDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *renter) updateTableName(table string) *renter {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.TenantID = field.NewString(table, "tenant_id")
	r.ConcreteRenterID = field.NewString(table, "concrete_renter_id")
	r.ConcreteRenterModel = field.NewString(table, "concrete_renter_model")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *renter) WithContext(ctx context.Context) *renterDo { return r.renterDo.WithContext(ctx) }

func (r renter) TableName() string { return r.renterDo.TableName() }

func (r renter) Alias() string { return r.renterDo.Alias() }

func (r renter) Columns(cols ...field.Expr) gen.Columns { return r.renterDo.Columns(cols...) }

func (r *renter) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *renter) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["tenant_id"] = r.TenantID
	r.fieldMap["concrete_renter_id"] = r.ConcreteRenterID
	r.fieldMap["concrete_renter_model"] = r.ConcreteRenterModel
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r renter) clone(db *gorm.DB) renter {
	r.renterDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r renter) replaceDB(db *gorm.DB) renter {
	r.renterDo.ReplaceDB(db)
	return r
}

type renterDo struct{ gen.DO }

func (r renterDo) Debug() *renterDo {
	return r.withDO(r.DO.Debug())
}

func (r renterDo) WithContext(ctx context.Context) *renterDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r renterDo) ReadDB() *renterDo {
	return r.Clauses(dbresolver.Read)
}

func (r renterDo) WriteDB() *renterDo {
	return r.Clauses(dbresolver.Write)
}

func (r renterDo) Session(config *gorm.Session) *renterDo {
	return r.withDO(r.DO.Session(config))
}

func (r renterDo) Clauses(conds ...clause.Expression) *renterDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r renterDo) Returning(value interface{}, columns ...string) *renterDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r renterDo) Not(conds ...gen.Condition) *renterDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r renterDo) Or(conds ...gen.Condition) *renterDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r renterDo) Select(conds ...field.Expr) *renterDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r renterDo) Where(conds ...gen.Condition) *renterDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r renterDo) Order(conds ...field.Expr) *renterDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r renterDo) Distinct(cols ...field.Expr) *renterDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r renterDo) Omit(cols ...field.Expr) *renterDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r renterDo) Join(table schema.Tabler, on ...field.Expr) *renterDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r renterDo) LeftJoin(table schema.Tabler, on ...field.Expr) *renterDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r renterDo) RightJoin(table schema.Tabler, on ...field.Expr) *renterDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r renterDo) Group(cols ...field.Expr) *renterDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r renterDo) Having(conds ...gen.Condition) *renterDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r renterDo) Limit(limit int) *renterDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r renterDo) Offset(offset int) *renterDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r renterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *renterDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r renterDo) Unscoped() *renterDo {
	return r.withDO(r.DO.Unscoped())
}

func (r renterDo) Create(values ...*dbmodel.Renter) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r renterDo) CreateInBatches(values []*dbmodel.Renter, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r renterDo) Save(values ...*dbmodel.Renter) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r renterDo) First() (*dbmodel.Renter, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodel.Renter), nil
	}
}

func (r renterDo) Take() (*dbmodel.Renter, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodel.Renter), nil
	}
}

func (r renterDo) Last() (*dbmodel.Renter, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodel.Renter), nil
	}
}

func (r renterDo) Find() ([]*dbmodel.Renter, error) {
	result, err := r.DO.Find()
	return result.([]*dbmodel.Renter), err
}

func (r renterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbmodel.Renter, err error) {
	buf := make([]*dbmodel.Renter, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r renterDo) FindInBatches(result *[]*dbmodel.Renter, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r renterDo) Attrs(attrs ...field.AssignExpr) *renterDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r renterDo) Assign(attrs ...field.AssignExpr) *renterDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r renterDo) Joins(fields ...field.RelationField) *renterDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r renterDo) Preload(fields ...field.RelationField) *renterDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r renterDo) FirstOrInit() (*dbmodel.Renter, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodel.Renter), nil
	}
}

func (r renterDo) FirstOrCreate() (*dbmodel.Renter, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodel.Renter), nil
	}
}

func (r renterDo) FindByPage(offset int, limit int) (result []*dbmodel.Renter, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r renterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r renterDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r renterDo) Delete(models ...*dbmodel.Renter) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *renterDo) withDO(do gen.Dao) *renterDo {
	r.DO = *do.(*gen.DO)
	return r
}
